## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed = pd.read_csv('df_preprocessed.csv')

In [3]:
data_preprocessed.head()

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0           0              0              0              0              1   
1           1              0              0              0              0   
2           2              0              0              0              1   
3           3              1              0              0              0   
4           4              0              0              0              1   

   Month Value  Day of the Week  Transportation Expense  Distance to Work  \
0            7                1                     289                36   
1            7                1                     118                13   
2            7                2                     179                51   
3            7                3                     279                 5   
4            7                3                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          0         2     1   
1   50                  239.554               31          0         1     0   
2   38                  239.554               31          0         0     0   
3   39                  239.554               24          0         2     0   
4   33                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

## Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0           0              0              0              0              1   
1           1              0              0              0              0   
2           2              0              0              0              1   
3           3              1              0              0              0   
4           4              0              0              0              1   

   Month Value  Day of the Week  Transportation Expense  Distance to Work  \
0            7                1                     289                36   
1            7                1                     118                13   
2            7                2                     179                51   
3            7                3                     279                 5   
4            7                3                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          0         2     1   
1   50                  239.554               31          0         1     0   
2   38                  239.554               31          0         0     0   
3   39                  239.554               24          0         2     0   
4   33                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

## A comment on the targets

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0           0              0              0              0              1   
1           1              0              0              0              0   
2           2              0              0              0              1   
3           3              1              0              0              0   
4           4              0              0              0              1   

   Month Value  Transportation Expense  Age  Body Mass Index  Education  \
0            7                     289   33               30          0   
1            7                     118   50               31          0   
2            7                     179   38               31          0   
3            7                     279   39               24          0   
4            7                     289   33               30          0   

   Children  Pets  Excessive Absenteeism  
0         2     1                      1  
1         1     0                      0  
2         0     0                      0  
3         2     0                      1  
4         2     1                      0

## Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 13)

In [14]:
data_with_targets.iloc[:,:14]

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0             0              0              0              0              1   
1             1              0              0              0              0   
2             2              0              0              0              1   
3             3              1              0              0              0   
4             4              0              0              0              1   
..          ...            ...            ...            ...            ...   
695         695              1              0              0              0   
696         696              1              0              0              0   
697         697              1              0              0              0   
698         698              0              0              0              1   
699         699              0              0              0              1   

     Month Value  Transportation Expense  Age  Body Mass Index  Education  \
0              7                     289   33               30          0   
1              7                     118   50               31          0   
2              7                     179   38               31          0   
3              7                     279   39               24          0   
4              7                     289   33               30          0   
..           ...                     ...  ...              ...        ...   
695            5                     179   40               22          1   
696            5                     225   28               24          0   
697            5                     330   28               25          1   
698            5                     235   32               25          1   
699            5                     291   40               25          0   

     Children  Pets  Excessive Absenteeism  
0           2     1                      1  
1           1     0                      0  
2           0     0                      0  
3           2     0                      1  
4           2     1                      0  
..        ...   ...                    ...  
695         2     0                      1  
696         1     2                      0  
697         0     0                      1  
698         0     0                      0  
699         1     1                      0  

[700 rows x 13 columns]

In [15]:
data_with_targets.iloc[:,:-1]

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0             0              0              0              0              1   
1             1              0              0              0              0   
2             2              0              0              0              1   
3             3              1              0              0              0   
4             4              0              0              0              1   
..          ...            ...            ...            ...            ...   
695         695              1              0              0              0   
696         696              1              0              0              0   
697         697              1              0              0              0   
698         698              0              0              0              1   
699         699              0              0              0              1   

     Month Value  Transportation Expense  Age  Body Mass Index  Education  \
0              7                     289   33               30          0   
1              7                     118   50               31          0   
2              7                     179   38               31          0   
3              7                     279   39               24          0   
4              7                     289   33               30          0   
..           ...                     ...  ...              ...        ...   
695            5                     179   40               22          1   
696            5                     225   28               24          0   
697            5                     330   28               25          1   
698            5                     235   32               25          1   
699            5                     291   40               25          0   

     Children  Pets  
0           2     1  
1           1     0  
2           0     0  
3           2     0  
4           2     1  
..        ...   ...  
695         2     0  
696         1     2  
697         0     0  
698         0     0  
699         1     1  

[700 rows x 12 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [17]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'reason_type_1', 'reason_type_2', 'reason_type_3',
       'reason_type_4', 'Month Value', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [20]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

C:\ProgramData\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Unnamed: 0', 'reason_type_1', 'reason_type_2',
                      'reason_type_3', 'reason_type_4', 'Month Value',
                      'Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets'])

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
0     -1.729578      -0.577350      -0.092981      -0.314485       0.821365   
1     -1.724629      -0.577350      -0.092981      -0.314485      -1.217485   
2     -1.719681      -0.577350      -0.092981      -0.314485       0.821365   
3     -1.714732       1.732051      -0.092981      -0.314485      -1.217485   
4     -1.709783      -0.577350      -0.092981      -0.314485       0.821365   
..          ...            ...            ...            ...            ...   
695    1.709783       1.732051      -0.092981      -0.314485      -1.217485   
696    1.714732       1.732051      -0.092981      -0.314485      -1.217485   
697    1.719681       1.732051      -0.092981      -0.314485      -1.217485   
698    1.724629      -0.577350      -0.092981      -0.314485       0.821365   
699    1.729578      -0.577350      -0.092981      -0.314485       0.821365   

     Month Value  Transportation Expense       Age  Body Mass Index  \
0       0.030796                1.005844 -0.536062         0.767431   
1       0.030796               -1.574681  2.130803         1.002633   
2       0.030796               -0.654143  0.248310         1.002633   
3       0.030796                0.854936  0.405184        -0.643782   
4       0.030796                1.005844 -0.536062         0.767431   
..           ...                     ...       ...              ...   
695    -0.568019               -0.654143  0.562059        -1.114186   
696    -0.568019                0.040034 -1.320435        -0.643782   
697    -0.568019                1.624567 -1.320435        -0.408580   
698    -0.568019                0.190942 -0.692937        -0.408580   
699    -0.568019                1.036026  0.562059        -0.408580   

     Education  Children      Pets  
0            0  0.880469  0.268487  
1            0 -0.019280 -0.589690  
2            0 -0.919030 -0.589690  
3            0  0.880469 -0.589690  
4            0  0.880469  0.268487  
..         ...       ...       ...  
695          1  0.880469 -0.589690  
696          0 -0.019280  1.126663  
697          1 -0.919030 -0.589690  
698          1 -0.919030 -0.589690  
699          0 -0.019280  0.268487  

[700 rows x 12 columns]

In [26]:
scaled_inputs.shape

(700, 12)

## Split the data into train & test and shuffle

### Import the relevant module

In [27]:
from sklearn.model_selection import train_test_split

### Split

In [28]:
train_test_split(scaled_inputs, targets)

[     Unnamed: 0  reason_type_1  reason_type_2  reason_type_3  reason_type_4  \
 308   -0.205372      -0.577350      -0.092981      -0.314485       0.821365   
 618    1.328732      -0.577350      -0.092981      -0.314485       0.821365   
 391    0.205372      -0.577350      -0.092981       3.179797      -1.217485   
 496    0.724988      -0.577350      -0.092981      -0.314485       0.821365   
 147   -1.002116      -0.577350      -0.092981      -0.314485       0.821365   
 ..          ...            ...            ...            ...            ...   
 77    -1.348527      -0.577350      -0.092981      -0.314485       0.821365   
 376    0.131141      -0.577350      -0.092981      -0.314485       0.821365   
 529    0.888296       1.732051      -0.092981      -0.314485      -1.217485   
 40    -1.531629      -0.577350      -0.092981      -0.314485       0.821365   
 401    0.254859      -0.577350      -0.092981       3.179797      -1.217485   
 
      Month Value  Transportation Expe

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [30]:
print (x_train.shape, y_train.shape)

(560, 12) (560,)


In [31]:
print (x_test.shape, y_test.shape)

(140, 12) (140,)


## Logistic regression with sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

LogisticRegression()

In [35]:
reg.score(x_train,y_train)

0.7821428571428571

### Manually check the accuracy

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [38]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
np.sum((model_outputs==y_train))

438

In [40]:
model_outputs.shape[0]

560

In [41]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7821428571428571

### Finding the intercept and coefficients

In [42]:
reg.intercept_

array([-0.1889362])

In [43]:
reg.coef_

array([[-0.24176547,  2.07380144,  0.34250594,  1.53172808,  1.31203691,
         0.00792613,  0.70073325, -0.18705066,  0.35107386, -0.19842476,
         0.36829133, -0.30367007]])

In [44]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'reason_type_1', 'reason_type_2', 'reason_type_3',
       'reason_type_4', 'Month Value', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0               Unnamed: 0    -0.241765
1            reason_type_1     2.073801
2            reason_type_2     0.342506
3            reason_type_3     1.531728
4            reason_type_4     1.312037
5              Month Value     0.007926
6   Transportation Expense     0.700733
7                      Age    -0.187051
8          Body Mass Index     0.351074
9                Education    -0.198425
10                Children     0.368291
11                    Pets    -0.303670

In [47]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.188936
1               Unnamed: 0    -0.241765
2            reason_type_1     2.073801
3            reason_type_2     0.342506
4            reason_type_3     1.531728
5            reason_type_4     1.312037
6              Month Value     0.007926
7   Transportation Expense     0.700733
8                      Age    -0.187051
9          Body Mass Index     0.351074
10               Education    -0.198425
11                Children     0.368291
12                    Pets    -0.303670

## Interpreting the coefficients

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.188936    0.827839
1               Unnamed: 0    -0.241765    0.785240
2            reason_type_1     2.073801    7.955006
3            reason_type_2     0.342506    1.408473
4            reason_type_3     1.531728    4.626164
5            reason_type_4     1.312037    3.713731
6              Month Value     0.007926    1.007958
7   Transportation Expense     0.700733    2.015230
8                      Age    -0.187051    0.829402
9          Body Mass Index     0.351074    1.420592
10               Education    -0.198425    0.820021
11                Children     0.368291    1.445263
12                    Pets    -0.303670    0.738104

In [50]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
2            reason_type_1     2.073801    7.955006
4            reason_type_3     1.531728    4.626164
5            reason_type_4     1.312037    3.713731
7   Transportation Expense     0.700733    2.015230
11                Children     0.368291    1.445263
9          Body Mass Index     0.351074    1.420592
3            reason_type_2     0.342506    1.408473
6              Month Value     0.007926    1.007958
8                      Age    -0.187051    0.829402
0                Intercept    -0.188936    0.827839
10               Education    -0.198425    0.820021
1               Unnamed: 0    -0.241765    0.785240
12                    Pets    -0.303670    0.738104

## Testing the model

In [51]:
reg.score(x_test,y_test)

0.7357142857142858

In [52]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.79395607, 0.20604393],
       [0.58574935, 0.41425065],
       [0.43518528, 0.56481472],
       [0.81715022, 0.18284978],
       [0.04896783, 0.95103217],
       [0.3474663 , 0.6525337 ],
       [0.21836036, 0.78163964],
       [0.10732408, 0.89267592],
       [0.69979554, 0.30020446],
       [0.67540146, 0.32459854],
       [0.53492634, 0.46507366],
       [0.18125249, 0.81874751],
       [0.03561979, 0.96438021],
       [0.70460674, 0.29539326],
       [0.26356061, 0.73643939],
       [0.50373811, 0.49626189],
       [0.58063962, 0.41936038],
       [0.45166403, 0.54833597],
       [0.43980929, 0.56019071],
       [0.04009795, 0.95990205],
       [0.69043108, 0.30956892],
       [0.81679242, 0.18320758],
       [0.46119627, 0.53880373],
       [0.46181054, 0.53818946],
       [0.23805531, 0.76194469],
       [0.72859057, 0.27140943],
       [0.54393962, 0.45606038],
       [0.90605301, 0.09394699],
       [0.2100249 , 0.7899751 ],
       [0.8178642 , 0.1821358 ],
       [0.

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
predicted_proba[:,1]

array([0.20604393, 0.41425065, 0.56481472, 0.18284978, 0.95103217,
       0.6525337 , 0.78163964, 0.89267592, 0.30020446, 0.32459854,
       0.46507366, 0.81874751, 0.96438021, 0.29539326, 0.73643939,
       0.49626189, 0.41936038, 0.54833597, 0.56019071, 0.95990205,
       0.30956892, 0.18320758, 0.53880373, 0.53818946, 0.76194469,
       0.27140943, 0.45606038, 0.09394699, 0.7899751 , 0.1821358 ,
       0.29942469, 0.76655903, 0.76003967, 0.45614657, 0.18195765,
       0.68011444, 0.1968225 , 0.8639658 , 0.43627465, 0.70177847,
       0.18882608, 0.43865714, 0.28146749, 0.10801352, 0.8203882 ,
       0.65277059, 0.65573116, 0.30652226, 0.22829444, 0.19326669,
       0.4451096 , 0.07082897, 0.7652622 , 0.20536975, 0.88547625,
       0.40383005, 0.91661885, 0.1939758 , 0.08530118, 0.0840939 ,
       0.65446558, 0.66728692, 0.21658939, 0.87113607, 0.27356423,
       0.31444527, 0.01131677, 0.29419873, 0.81087833, 0.40178869,
       0.29002153, 0.08515904, 0.91243947, 0.41029693, 0.58341

## Save the model

In [55]:
import pickle

In [56]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)